// Generated by Wrangler on Tue Jul 30 2024 11:46:09 GMT+1000 (Australian Eastern Standard Time)
// by running `wrangler types`

interface Env {
	SECRET: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
}
