#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-encdec-service"
main = "src/index.ts"
compatibility_date = "2024-07-25"
compatibility_flags = [ "nodejs_compat" ]

[vars]
SECRET="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"